export const SIGNUPUSER = "SIGNUPUSER";
export const SIGNUPUSER_SUCCESS = " SIGNUPUSER_SUCCESS";
export const SIGNUPUSER_FAIL = "SIGNUPUSER_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const SIGNUPLOGINSUCC = "SIGNUPLOGINSUCC";

SIGNUPLOGINSUCC;

export const REST_PASSWORD = "REST_PASSWORD";
export const REST_PASSWORD_FAIL = "REST_PASSWORD_FAIL";
export const REST_PASSWORD_SUCC = "REST_PASSWORD_SUCC";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER = "LOGIN_USER";

export const RECIPE_VALUE = "RECIPE_VALUE";
export const GET_RECIPES = "GET_RECIPES";
export const GET_RECIPE_ING = "GET_RECIPE_ING";

export const LOVED_RECIPES = "LOVED_RECIPES";
export const DELETE_LOVED_RECIPES = "DELETE_LOVED_RECIPES";
export const LOVED_RECIPES_TO_INGPAGE = "LOVED_RECIPES_TO_INGPAGE";
export const LOVED_RECIPES_FETCH = "LOVED_RECIPES_FETCH";

export const ADD_TO_SHOPPING_LIST = "ADD_TO_SHOPPING_LIST";
export const REMOVE_FROM_SHOPPING_LIST = "REMOVE_FROM_SHOPPING_LIST";
export const SHOPPINGLIST_TO_ITEMLIST = "SHOPPINGLIST_TO_ITEMLIST";
export const SHOPPINGLIST_FETCH = "SHOPPINGLIST_FETCH";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const FETCH_PROFILE = "FETCH_PROFILE";
